version: "3.9"

services:
  reverse-proxy:
    container_name: proxy_app
    image: traefik:v2.5
    restart: always
    environment:
      TRAEFIK_ADMIN_USERNAME: $TRAEFIK_ADMIN_USERNAME
      TRAEFIK_ADMIN_PASSWORD: $TRAEFIK_ADMIN_PASSWORD
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./lets-encrypt:/lets-encrypt
      - ./traefik.yml:/traefik.yml
      - ./traefik_dynamic.yml:/traefik_dynamic.yml

networks:
  proxy:
    external: true
