services:
  reverse-proxy:
    container_name: proxy_app
    image: traefik:v2.9
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/config:ro
      - ./traefik.yml:/traefik.yml:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy

networks:
  proxy:
    external: true
