services:
  reverse-proxy:
    container_name: proxy_app
    image: traefik:v2.9
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./lets-encrypt:/lets-encrypt
      - ./.users:/.users
      - ./traefik.yml:/traefik.yml
      - ./traefik_dynamic.yml:/traefik_dynamic.yml
    networks:
      - proxy

networks:
  proxy:
    external: true
