http:
  middlewares:
    simpleAuth:
      basicAuth:
        usersfile: "/.users"

  routers:
    traefik:
      rule: "Host(`traefik.lab-agora.fr`)"
      entrypoints:
        - "websecure"
      middlewares:
        - "simpleAuth"
      service: "traefik@internal"
      tls:
        certResolver: "lets-encrypt"
