http:
  middlewares:
    auth:
      basicAuth:
        usersfile: "/.users"

  routers:
    local_dashboard:
      rule: "Host(`localhost`)"
      entrypoints:
        - "web"
      service: "api@internal"

    public_dashbord:
      rule: "Host(`traefik.lab-agora.fr`)"
      entrypoints:
        - "web"
      middlewares:
        - "auth"
      service: "api@internal"
      # tls:
      #   certResolver: "lets-encrypt"
