http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - "${TRAEFIK_ADMIN_USERNAME}:${TRAEFIK_ADMIN_PASSWORD}"

  routers:
    api:
      rule: "Host(`traefik.lab-agora.fr`)"
      entrypoints:
        - "websecure"
      middlewares:
        - "simpleAuth"
      service: "api@internal"
      tls:
        certResolver: "lets-encrypt"
