api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

log:
  level: "INFO"

providers:
  docker:
    network: "proxy"
    watch: true
  file:
    directory: "/config"
