http:
  middlewares:
    simpleAuth:
      basicAuth:
        usersfile: "/.users"

  routers:
    api:
      rule: "Host(`localhost`)"
      entrypoints:
        - "web"
      middlewares:
        - "simpleAuth"
      service: "api@internal"
      # tls:
      #   certResolver: "lets-encrypt"
