http:
  middlewares:
    auth:
      basicAuth:
        usersfile: "/.users"

  routers:
    local_dashboard:
      rule: "Host(`localhost`)"
      entrypoints:
        - "web"
      service: "api@internal"

    private_dashboard:
      rule: "Host(`10.100.0.170`)"
      entrypoints:
        - "web"
      service: "api@internal"
      middlewares:
        - "auth"

    public_dashbord:
      rule: "Host(`traefik.labagora.e-cancer.fr`)"
      entrypoints:
        - "web"
      service: "api@internal"
      middlewares:
        - "auth"
      # tls:
      #   certResolver: "lets-encrypt"
