http:
  middlewares:
    basic_authentication:
      basicAuth:
        usersfile: "/config/.users"
    https_redirection:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    local_dashboard:
      rule: "Host(`localhost`)"
      entrypoints:
        - "web"
        # - "websecure"
      # middlewares:
      #   - "https_redirection"
      service: "api@internal"
      # tls: true

    private_dashboard:
      rule: "Host(`10.100.0.170`)"
      entrypoints:
        - "web"
      middlewares:
        - "basic_authentication"
      service: "api@internal"

    public_dashbord:
      rule: "Host(`traefik-labagora.e-cancer.fr`)"
      entrypoints:
        - "websecure"
      middlewares:
        - "basic_authentication"
        - "https_redirection"
      service: "api@internal"
      tls: true

tls:
  certificates:
    - certFile: /config/ecancer.fr.crt
      keyFile: /config/ecancer.fr.key
      stores:
        - default
  stores:
    defaults:
      defaultCertificate:
        certFile: /config/ecancer.fr.crt
        keyFile: /config/ecancer.fr.key
